#!/bin/bash

singletonize
# Set Environment
# set -Eeuo pipefail

# Set Variable
XDG_DATA_HOME="$HOME/.local/share"
PRIMITIVE_SCRIPTS_LOCATION="$HOME/.config/wofi/scripts"
DESKTOP_SCRIPTS_LOCATION="$XDG_DATA_HOME/applications"

generateScript(){
  name=$(expr match $1 '\(.*\)\.sh$')
  cat << EOF > $DESKTOP_SCRIPTS_LOCATION/$name.desktop
[Desktop Entry]
Type=Application
Name=${name}
Exec=/bin/bash $2/$1
EOF
}

deleteScript(){
  rm $DESKTOP_SCRIPTS_LOCATION/$(expr match $1 '\(.*\)\.sh').desktop
}

inotifywait -m -e create -e delete -e moved_from -e moved_to $PRIMITIVE_SCRIPTS_LOCATION \
  | while read -r NEWFILE
do
  log info "\n------ started "$NEWFILE"------"
  created=$(echo ${NEWFILE} \
    | grep -E "^.* (CREATE|MOVED_TO) .*\.sh$" \
    | awk '{print $3}')
  deleted=$(echo ${NEWFILE} \
    | grep -E "^.* (DELETE|MOVED_FROM) .*\.sh$" \
    | awk '{print $3}')
  if [[ ${#deleted} -ge 1 ]];then
    log info "deleted: $deleted"
    deleteScript $deleted
  fi
  if [[ ${#created} -ge 1 ]];then
    log info "created: $created"
    generateScript $created $PRIMITIVE_SCRIPTS_LOCATION
  fi
  log info "------ ended ------\n"
done

